ALTER TABLE "Order" ADD COLUMN "paidAt" TIMESTAMP(3), ADD COLUMN "confirmedAt" TIMESTAMP(3);
ALTER TABLE "Payment" ADD COLUMN "paymentMethod" TEXT, ADD COLUMN "transactionTime" TIMESTAMP(3);
CREATE TABLE "RazorpayWebhookEvent" ("id" TEXT PRIMARY KEY,"eventId" TEXT NOT NULL UNIQUE,"eventType" TEXT NOT NULL,"payload" JSONB NOT NULL,"processedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
