import { useEffect, useState } from "react";
import { fetchMedia, type AdminMedia } from "@/services/adminApi";
import { mediaVariantUrl } from "@/lib/media";

export default function MediaPicker({token,value,onChange,max=1,valueType="id",label="Select existing media"}:{token?:string;value:string[];onChange:(value:string[])=>void;max?:number;valueType?:"id"|"url";label?:string}){
  const [items,setItems]=useState<AdminMedia[]>([]);const [selected,setSelected]=useState("");
  useEffect(()=>{void fetchMedia(token).then(result=>setItems(result.value)).catch(()=>setItems([]));},[token]);
  const key=(item:AdminMedia)=>valueType==="id"?item.id:item.url;
  const add=()=>{if(selected&&!value.includes(selected)&&value.length<max)onChange([...value,selected]);setSelected("");};
  const move=(index:number,direction:-1|1)=>{const next=[...value];const target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];onChange(next);};
  return <fieldset className="space-y-2 rounded-md border p-3"><legend className="px-1 text-sm font-medium">{label}</legend><div className="flex gap-2"><select aria-label={label} className="min-w-0 flex-1 rounded-md border bg-background px-3 py-2 text-sm" value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Choose an image…</option>{items.filter(item=>!value.includes(key(item))).map(item=><option key={item.id} value={key(item)}>{item.filename} ({item.width??"?"}×{item.height??"?"})</option>)}</select><button type="button" disabled={!selected||value.length>=max} onClick={add} className="rounded border px-3 py-2 text-sm disabled:opacity-50">Add</button></div>{value.map((selectedValue,index)=>{const item=items.find(candidate=>key(candidate)===selectedValue);return <div key={selectedValue} className="flex items-center gap-2 rounded border p-2"><img src={mediaVariantUrl(item?.url??selectedValue,"adminThumbnail")} alt={item?.altText??item?.filename??"Selected media"} className="h-12 w-12 rounded object-cover"/><span className="min-w-0 flex-1 truncate text-xs">{item?.filename??selectedValue}</span>{max>1&&<><button type="button" aria-label="Move image earlier" disabled={index===0} onClick={()=>move(index,-1)} className="rounded border px-2 disabled:opacity-40">↑</button><button type="button" aria-label="Move image later" disabled={index===value.length-1} onClick={()=>move(index,1)} className="rounded border px-2 disabled:opacity-40">↓</button></>}<button type="button" onClick={()=>onChange(value.filter(entry=>entry!==selectedValue))} className="rounded border border-destructive px-2 text-destructive">Remove</button></div>;})}</fieldset>;
}
