import { createContext, useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import type { Product, CartItem, Coupon } from "@/types/store";
import { apiFetch } from "@/services/api";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "sonner";

interface CartContextType { cartItems:CartItem[]; itemCount:number; appliedCoupon:Coupon|null; loading:boolean; error:string|null; addToCart:(product:Product,quantity:number)=>void; removeFromCart:(sku:string)=>void; updateQuantity:(sku:string,quantity:number)=>void; clearCart:()=>void; applyCoupon:(code:string)=>boolean; removeCoupon:()=>void; subtotal:number; discount:number; shipping:number; tax:number; total:number; }
type ServerCart={product:Product;quantity:number}; const key="autoforge_cart_items";
const token=()=>localStorage.getItem("autoforge_access_token"); const headers=()=>({Authorization:`Bearer ${token()}`});
const normalize=(rows:ServerCart[]):CartItem[]=>rows.filter(r=>r.product).map(r=>({product:r.product,quantity:r.quantity}));
export const CartContext=createContext<CartContextType|undefined>(undefined);
export function CartProvider({children}:{children:ReactNode}){
 const {isAuthenticated,loading:authLoading}=useAuth(); const [cartItems,setCartItems]=useState<CartItem[]>([]);const [appliedCoupon,setAppliedCoupon]=useState<Coupon|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const busy=useRef(new Set<string>());
 const guest=()=>{try{return JSON.parse(localStorage.getItem(key)??"[]") as CartItem[]}catch{return[]}};const saveGuest=(items:CartItem[])=>localStorage.setItem(key,JSON.stringify(items));
 const load=useCallback(async()=>{if(authLoading)return;setLoading(true);setError(null);try{if(!isAuthenticated){setCartItems(guest());return;}const guestItems=guest();for(const item of guestItems){await apiFetch("/api/cart",{method:"POST",headers:headers(),body:JSON.stringify({productId:item.product.id,quantity:Math.min(item.quantity,item.product.stockQuantity)})});}if(guestItems.length)localStorage.removeItem(key);setCartItems(normalize(await apiFetch<ServerCart[]>("/api/cart",{headers:headers()})));}catch(e){setError(e instanceof Error?e.message:"Unable to load cart");setCartItems([]);}finally{setLoading(false);}},[authLoading,isAuthenticated]);
 useEffect(()=>{void load();},[load]);
 const mutate=useCallback(async(action:string,product:Product,quantity?:number)=>{if(busy.current.has(product.id))return;busy.current.add(product.id);try{if(!isAuthenticated){setCartItems(prev=>{const existing=prev.find(x=>x.product.sku===product.sku);const next=action==="remove"?prev.filter(x=>x.product.sku!==product.sku):existing?prev.map(x=>x.product.sku===product.sku?{...x,quantity:quantity??x.quantity}:x):[...prev,{product,quantity:quantity??1}];saveGuest(next);return next;});return;}if(action==="add")await apiFetch("/api/cart",{method:"POST",headers:headers(),body:JSON.stringify({productId:product.id,quantity})});if(action==="update")await apiFetch("/api/cart",{method:"PATCH",headers:headers(),body:JSON.stringify({productId:product.id,quantity})});if(action==="remove")await apiFetch(`/api/cart/${product.id}`,{method:"DELETE",headers:headers()});setCartItems(normalize(await apiFetch<ServerCart[]>("/api/cart",{headers:headers()})));}catch(e){toast.error(e instanceof Error?e.message:"Cart update failed");}finally{busy.current.delete(product.id);}},[isAuthenticated]);
 const addToCart=(p:Product,q:number)=>{if(q>0){void mutate("add",p,q);toast.success(`Added "${p.name}" to cart.`);}};const removeFromCart=(sku:string)=>{const p=cartItems.find(x=>x.product.sku===sku)?.product;if(p){void mutate("remove",p);toast.info(`Removed "${p.name}" from cart.`);}};const updateQuantity=(sku:string,q:number)=>{const p=cartItems.find(x=>x.product.sku===sku)?.product;if(!p)return;if(q<1)removeFromCart(sku);else void mutate("update",p,q)};
 const subtotal=cartItems.reduce((n,x)=>n+x.product.price*x.quantity,0);const discount=appliedCoupon?appliedCoupon.type==="percent"?subtotal*appliedCoupon.value/100:Math.min(subtotal,appliedCoupon.value):0;const shipping=subtotal&&subtotal-discount<999?99:0;const tax=(subtotal-discount)*18/118;
 const value=useMemo(()=>({cartItems,itemCount:cartItems.reduce((n,x)=>n+x.quantity,0),appliedCoupon,loading,error,addToCart,removeFromCart,updateQuantity,clearCart:()=>{if(!isAuthenticated){saveGuest([]);setCartItems([])}},applyCoupon:(code:string)=>{const c=code==="AUTOFIRST"?{code,type:"percent" as const,value:10}:null;if(c)setAppliedCoupon(c);return!!c},removeCoupon:()=>setAppliedCoupon(null),subtotal,discount,shipping,tax,total:Math.max(0,subtotal-discount+shipping)}),[cartItems,appliedCoupon,loading,error,subtotal,discount,shipping,tax,isAuthenticated]);return <CartContext.Provider value={value}>{children}</CartContext.Provider>;
}
