import { createContext, useCallback, useEffect, useRef, useState, type ReactNode } from "react";
import type { Product, CartItem } from "@/types/store";
import { apiFetch, authHeaders } from "@/services/api";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "sonner";

interface CartContextType { cartItems:CartItem[]; itemCount:number; loading:boolean; error:string|null; addToCart:(product:Product,quantity:number)=>void; removeFromCart:(sku:string)=>void; updateQuantity:(sku:string,quantity:number)=>void; clearCart:()=>void; subtotal:number; shipping:number; tax:number; total:number; }
type ServerCart={product:Product;quantity:number}; const key="autoforge_cart_items";
const normalize=(rows:ServerCart[]):CartItem[]=>rows.filter(r=>r.product).map(r=>({product:r.product,quantity:r.quantity}));
export const CartContext=createContext<CartContextType|undefined>(undefined);
export function CartProvider({children}:{children:ReactNode}){
 const {isAuthenticated,loading:authLoading}=useAuth(); const [cartItems,setCartItems]=useState<CartItem[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const busy=useRef(new Set<string>());
 const guest=()=>{try{return JSON.parse(localStorage.getItem(key)??"[]") as CartItem[]}catch{return[]}};const saveGuest=(items:CartItem[])=>localStorage.setItem(key,JSON.stringify(items));
 const load=useCallback(async()=>{if(authLoading)return;setLoading(true);setError(null);try{if(!isAuthenticated){setCartItems(guest());return;}const guestItems=guest();for(const item of guestItems){await apiFetch("/api/cart",{method:"POST",headers:authHeaders(),body:JSON.stringify({productId:item.product.id,quantity:Math.min(item.quantity,item.product.stockQuantity)})});}if(guestItems.length)localStorage.removeItem(key);setCartItems(normalize(await apiFetch<ServerCart[]>("/api/cart",{headers:authHeaders()})));}catch(e){setError(e instanceof Error?e.message:"Unable to load cart");setCartItems([]);}finally{setLoading(false);}},[authLoading,isAuthenticated]);
 useEffect(()=>{void load();},[load]);
 const mutate=useCallback(async(action:string,product:Product,quantity?:number):Promise<boolean>=>{if(busy.current.has(product.id))return false;busy.current.add(product.id);try{if(!isAuthenticated){setCartItems(prev=>{const existing=prev.find(x=>x.product.sku===product.sku);const next=action==="remove"?prev.filter(x=>x.product.sku!==product.sku):existing?prev.map(x=>x.product.sku===product.sku?{...x,quantity:quantity??x.quantity}:x):[...prev,{product,quantity:quantity??1}];saveGuest(next);return next;});return true;}if(action==="add")await apiFetch("/api/cart",{method:"POST",headers:authHeaders(),body:JSON.stringify({productId:product.id,quantity})});if(action==="update")await apiFetch("/api/cart",{method:"PATCH",headers:authHeaders(),body:JSON.stringify({productId:product.id,quantity})});if(action==="remove")await apiFetch(`/api/cart/${product.id}`,{method:"DELETE",headers:authHeaders()});setCartItems(normalize(await apiFetch<ServerCart[]>("/api/cart",{headers:authHeaders()})));return true;}catch(e){toast.error(e instanceof Error?e.message:"Cart update failed");return false;}finally{busy.current.delete(product.id);}},[isAuthenticated]);
 const addToCart=(p:Product,q:number)=>{if(q>0)void mutate("add",p,q).then(updated=>{if(updated)toast.success(`Added "${p.name}" to cart.`);});};const removeFromCart=(sku:string)=>{const p=cartItems.find(x=>x.product.sku===sku)?.product;if(p){void mutate("remove",p).then(updated=>{if(updated)toast.info(`Removed "${p.name}" from cart.`);});}};const updateQuantity=(sku:string,q:number)=>{const p=cartItems.find(x=>x.product.sku===sku)?.product;if(!p)return;if(q<1)removeFromCart(sku);else void mutate("update",p,q)};
 const subtotal=cartItems.reduce((n,x)=>n+x.product.price*x.quantity,0);const shipping=0;const tax=subtotal*18/118;
 const clearCart=()=>{if(!isAuthenticated){saveGuest([]);setCartItems([]);return;}const current=[...cartItems];void Promise.all(current.map(item=>apiFetch(`/api/cart/${item.product.id}`,{method:"DELETE",headers:authHeaders()}))).then(()=>setCartItems([])).catch(e=>toast.error(e instanceof Error?e.message:"Unable to clear cart"));};
 const value:CartContextType={cartItems,itemCount:cartItems.reduce((n,x)=>n+x.quantity,0),loading,error,addToCart,removeFromCart,updateQuantity,clearCart,subtotal,shipping,tax,total:subtotal};return <CartContext.Provider value={value}>{children}</CartContext.Provider>;
}
