import { createContext,useCallback,useEffect,useRef,useState,type ReactNode } from "react";
import type { Product } from "@/types/store";
import { apiFetch, authHeaders } from "@/services/api";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "sonner";
interface WishlistContextType{wishlistItems:Product[];loading:boolean;addToWishlist:(p:Product)=>void;removeFromWishlist:(sku:string)=>void;isInWishlist:(sku:string)=>boolean}
type ServerItem={product:Product};const key="autoforge_wishlist_items";
export const WishlistContext=createContext<WishlistContextType|undefined>(undefined);
export function WishlistProvider({children}:{children:ReactNode}){const {isAuthenticated,loading:authLoading}=useAuth();const [wishlistItems,setItems]=useState<Product[]>([]);const [loading,setLoading]=useState(true);const busy=useRef(new Set<string>());const guest=()=>{try{return JSON.parse(localStorage.getItem(key)??"[]") as Product[]}catch{return[]}};
 const load=useCallback(async()=>{if(authLoading)return;setLoading(true);try{if(!isAuthenticated){setItems(guest());return;}const g=guest();for(const p of g)await apiFetch("/api/wishlist",{method:"POST",headers:authHeaders(),body:JSON.stringify({productId:p.id})});if(g.length)localStorage.removeItem(key);const rows=await apiFetch<ServerItem[]>("/api/wishlist",{headers:authHeaders()});setItems(rows.filter(x=>x.product).map(x=>x.product));}catch{setItems([])}finally{setLoading(false)}},[authLoading,isAuthenticated]);useEffect(()=>{void load()},[load]);
 const addToWishlist=(p:Product)=>{if(busy.current.has(p.id)||wishlistItems.some(x=>x.sku===p.sku))return;busy.current.add(p.id);void (async()=>{try{if(!isAuthenticated){const next=[...wishlistItems,p];localStorage.setItem(key,JSON.stringify(next));setItems(next)}else{await apiFetch("/api/wishlist",{method:"POST",headers:authHeaders(),body:JSON.stringify({productId:p.id})});await load()}toast.success(`Added "${p.name}" to wishlist.`)}catch(e){toast.error(e instanceof Error?e.message:"Wishlist update failed")}finally{busy.current.delete(p.id)}})()};
 const removeFromWishlist=(sku:string)=>{const p=wishlistItems.find(x=>x.sku===sku);if(!p)return;void(async()=>{try{if(!isAuthenticated){const next=wishlistItems.filter(x=>x.sku!==sku);localStorage.setItem(key,JSON.stringify(next));setItems(next)}else{await apiFetch(`/api/wishlist/${p.id}`,{method:"DELETE",headers:authHeaders()});setItems(prev=>prev.filter(x=>x.sku!==sku))}toast.info(`Removed "${p.name}" from wishlist.`)}catch(e){toast.error(e instanceof Error?e.message:"Wishlist update failed")}})()};return <WishlistContext.Provider value={{wishlistItems,loading,addToWishlist,removeFromWishlist,isInWishlist:(sku)=>wishlistItems.some(x=>x.sku===sku)}}>{children}</WishlistContext.Provider>}
